### ISSUE TITLE
Can I deploy it using github pages?

### ISSUE THREAD

**Issue by rudrakshkarpe** [kausko/Portfolio#21]
- I'd like to know if deployment of this portfolio template is** possible with GitHub pages only.

**Comment by kausko** [comment]
Hello @rudrakshkarpe,

This template makes use of [`getStaticProps()`](https://nextjs.org/docs/basic-features/data-fetching/get-static-props) and [On-Demand Revalidation](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#on-demand-revalidation) to fetch the latest information about your GitHub repositories in (almost) real-time. This happens on the server-side at build-time and after the `revalidation` period (a minute) has passed.

Since GitHub Pages is a **static** site-hosting service, your repository information may not revalidate after deployment. If you're okay with that, feel free to deploy it on GitHub Pages. You can refer to these resources for deploying it on GitHub Pages:

- https://github.com/gregrickaby/nextjs-github-pages
- https://dev.to/github/how-to-host-a-static-nextjs-site-on-github-pages-4pe0
- https://javascript.plainenglish.io/deploy-your-next-js-app-on-github-pages-using-the-github-action-525271137409

I would really recommend using a hosting service that supports Incremental Static Regeneration (ISR) and/or Server-Side Rendering (SSR) like Vercel or Netlify for this repository.

Thanks for considering my template. If this helped, let me know so that I can close this issue.

**Comment by rudrakshkarpe** [comment]
Yes, this helped a lot, thanks for the much broader explanation on the topic!
It's great to connect with you :)
